begin;

-- Tabla base para resolver roles cuando el JWT no trae el rol de negocio.
-- Bootstrap: crea el primer SUPERADMIN desde SQL o usando service_role.
create table if not exists public.perfiles (
  id uuid primary key references auth.users(id) on delete cascade,
  rol text not null default 'CLIENTE',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint perfiles_rol_check check (upper(rol) in ('SUPERADMIN', 'ADMIN', 'EMPLEADO', 'VENDEDOR', 'CLIENTE'))
);

-- Tabla remota de auditoria/drenado usada por el motor offline-first.
create table if not exists public.transacciones_sync (
  id bigint generated by default as identity primary key,
  accion text not null,
  payload jsonb not null,
  timestamp timestamptz not null,
  estado text not null default 'PENDING',
  created_at timestamptz not null default now(),
  constraint transacciones_sync_estado_check check (estado in ('PENDING', 'PROCESSING', 'FAILED'))
);

alter table if exists public.transacciones_sync add column if not exists accion text;
alter table if exists public.transacciones_sync add column if not exists payload jsonb;
alter table if exists public.transacciones_sync add column if not exists timestamp timestamptz;
alter table if exists public.transacciones_sync add column if not exists estado text default 'PENDING';
alter table if exists public.transacciones_sync add column if not exists created_at timestamptz default now();

create or replace function public.normalize_app_role(raw_role text)
returns text
language sql
immutable
as $$
  select case
    when upper(coalesce(nullif(raw_role, ''), 'CLIENTE')) in ('SUPERADMIN', 'ADMIN') then 'SUPERADMIN'
    when upper(coalesce(nullif(raw_role, ''), 'CLIENTE')) in ('EMPLEADO', 'VENDEDOR') then 'EMPLEADO'
    else 'CLIENTE'
  end;
$$;

create or replace function public.current_app_role()
returns text
language plpgsql
stable
security definer
set search_path = public, auth, pg_temp
set row_security = off
as $$
declare
  jwt_role text;
  profile_role text;
begin
  jwt_role := coalesce(
    auth.jwt() ->> 'app_role',
    auth.jwt() ->> 'rol',
    auth.jwt() -> 'app_metadata' ->> 'app_role',
    auth.jwt() -> 'app_metadata' ->> 'rol',
    auth.jwt() -> 'app_metadata' ->> 'role',
    auth.jwt() -> 'user_metadata' ->> 'app_role',
    auth.jwt() -> 'user_metadata' ->> 'rol',
    auth.jwt() -> 'user_metadata' ->> 'role'
  );

  if public.normalize_app_role(jwt_role) <> 'CLIENTE' then
    return public.normalize_app_role(jwt_role);
  end if;

  select p.rol
    into profile_role
    from public.perfiles as p
   where p.id = auth.uid()
   limit 1;

  return public.normalize_app_role(profile_role);
end;
$$;

grant execute on function public.normalize_app_role(text) to anon, authenticated;
grant execute on function public.current_app_role() to anon, authenticated;

alter table public.perfiles enable row level security;
alter table public.perfiles force row level security;

drop policy if exists perfiles_select_own_or_superadmin on public.perfiles;
drop policy if exists perfiles_insert_superadmin on public.perfiles;
drop policy if exists perfiles_update_superadmin on public.perfiles;
drop policy if exists perfiles_delete_superadmin on public.perfiles;

create policy perfiles_select_own_or_superadmin
on public.perfiles
for select
to authenticated
using (id = auth.uid() or public.current_app_role() = 'SUPERADMIN');

create policy perfiles_insert_superadmin
on public.perfiles
for insert
to authenticated
with check (public.current_app_role() = 'SUPERADMIN');

create policy perfiles_update_superadmin
on public.perfiles
for update
to authenticated
using (public.current_app_role() = 'SUPERADMIN')
with check (public.current_app_role() = 'SUPERADMIN');

create policy perfiles_delete_superadmin
on public.perfiles
for delete
to authenticated
using (public.current_app_role() = 'SUPERADMIN');

grant select on public.perfiles to authenticated;
grant insert, update, delete on public.perfiles to authenticated;

do $$
begin
  if to_regclass('public.productos') is not null then
    execute 'alter table public.productos enable row level security';
    execute 'alter table public.productos force row level security';

    execute 'drop policy if exists productos_select_public on public.productos';
    execute 'drop policy if exists productos_insert_superadmin on public.productos';
    execute 'drop policy if exists productos_update_superadmin on public.productos';
    execute 'drop policy if exists productos_delete_superadmin on public.productos';

    execute 'create policy productos_select_public on public.productos for select to anon, authenticated using (true)';
    execute 'create policy productos_insert_superadmin on public.productos for insert to authenticated with check (public.current_app_role() = ''SUPERADMIN'')';
    execute 'create policy productos_update_superadmin on public.productos for update to authenticated using (public.current_app_role() = ''SUPERADMIN'') with check (public.current_app_role() = ''SUPERADMIN'')';
    execute 'create policy productos_delete_superadmin on public.productos for delete to authenticated using (public.current_app_role() = ''SUPERADMIN'')';

    execute 'grant select on public.productos to anon, authenticated';
    execute 'grant insert, update, delete on public.productos to authenticated';
  end if;
end $$;

do $$
begin
  if to_regclass('public.materias_primas') is not null then
    execute 'alter table public.materias_primas enable row level security';
    execute 'alter table public.materias_primas force row level security';

    execute 'drop policy if exists materias_primas_select_staff on public.materias_primas';
    execute 'drop policy if exists materias_primas_insert_superadmin on public.materias_primas';
    execute 'drop policy if exists materias_primas_update_superadmin on public.materias_primas';
    execute 'drop policy if exists materias_primas_delete_superadmin on public.materias_primas';

    execute 'create policy materias_primas_select_staff on public.materias_primas for select to authenticated using (public.current_app_role() in (''SUPERADMIN'', ''EMPLEADO''))';
    execute 'create policy materias_primas_insert_superadmin on public.materias_primas for insert to authenticated with check (public.current_app_role() = ''SUPERADMIN'')';
    execute 'create policy materias_primas_update_superadmin on public.materias_primas for update to authenticated using (public.current_app_role() = ''SUPERADMIN'') with check (public.current_app_role() = ''SUPERADMIN'')';
    execute 'create policy materias_primas_delete_superadmin on public.materias_primas for delete to authenticated using (public.current_app_role() = ''SUPERADMIN'')';

    execute 'grant select on public.materias_primas to authenticated';
    execute 'grant insert, update, delete on public.materias_primas to authenticated';
  end if;
end $$;

do $$
begin
  if to_regclass('public.recetas') is not null then
    execute 'alter table public.recetas enable row level security';
    execute 'alter table public.recetas force row level security';

    execute 'drop policy if exists recetas_select_staff on public.recetas';
    execute 'drop policy if exists recetas_insert_superadmin on public.recetas';
    execute 'drop policy if exists recetas_update_superadmin on public.recetas';
    execute 'drop policy if exists recetas_delete_superadmin on public.recetas';

    execute 'create policy recetas_select_staff on public.recetas for select to authenticated using (public.current_app_role() in (''SUPERADMIN'', ''EMPLEADO''))';
    execute 'create policy recetas_insert_superadmin on public.recetas for insert to authenticated with check (public.current_app_role() = ''SUPERADMIN'')';
    execute 'create policy recetas_update_superadmin on public.recetas for update to authenticated using (public.current_app_role() = ''SUPERADMIN'') with check (public.current_app_role() = ''SUPERADMIN'')';
    execute 'create policy recetas_delete_superadmin on public.recetas for delete to authenticated using (public.current_app_role() = ''SUPERADMIN'')';

    execute 'grant select on public.recetas to authenticated';
    execute 'grant insert, update, delete on public.recetas to authenticated';
  end if;
end $$;

alter table public.transacciones_sync enable row level security;
alter table public.transacciones_sync force row level security;

drop policy if exists transacciones_sync_insert_staff on public.transacciones_sync;
drop policy if exists transacciones_sync_select_superadmin on public.transacciones_sync;
drop policy if exists transacciones_sync_update_superadmin on public.transacciones_sync;
drop policy if exists transacciones_sync_delete_superadmin on public.transacciones_sync;

create policy transacciones_sync_insert_staff
on public.transacciones_sync
for insert
to authenticated
with check (public.current_app_role() in ('SUPERADMIN', 'EMPLEADO'));

create policy transacciones_sync_select_superadmin
on public.transacciones_sync
for select
to authenticated
using (public.current_app_role() = 'SUPERADMIN');

create policy transacciones_sync_update_superadmin
on public.transacciones_sync
for update
to authenticated
using (public.current_app_role() = 'SUPERADMIN')
with check (public.current_app_role() = 'SUPERADMIN');

create policy transacciones_sync_delete_superadmin
on public.transacciones_sync
for delete
to authenticated
using (public.current_app_role() = 'SUPERADMIN');

grant insert, select, update, delete on public.transacciones_sync to authenticated;
grant usage, select on all sequences in schema public to authenticated;

commit;
